//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitchenPrintSet
    {
        public int Id { get; set; }
        public string ServiceIP { get; set; }
        public int AutoBoot { get; set; }
        public int RefreshPeriod { get; set; }
        public int ServerAutoStart { get; set; }
        public int StartTime { get; set; }
        public int LimitPrint { get; set; }
        public int LimitTime { get; set; }
    }
}
