//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaPrintPlan
    {
        public AreaPrintPlan()
        {
            this.DishPrint = new HashSet<DishPrint>();
            this.MaterialPrint = new HashSet<MaterialPrint>();
        }
    
        public int AreaPlanId { get; set; }
        public string PlanName { get; set; }
        public int AreaId { get; set; }
        public int BasicPlanId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public int Status { get; set; }
    
        public virtual BasicPrintPlan BasicPrintPlan { get; set; }
        public virtual ICollection<DishPrint> DishPrint { get; set; }
        public virtual ICollection<MaterialPrint> MaterialPrint { get; set; }
    }
}
