//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashType
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CashBaseTypeId { get; set; }
        public int UseingKeys { get; set; }
        public string Keys { get; set; }
        public int IsScore { get; set; }
        public int ReceptionUseing { get; set; }
        public int SupplierUsing { get; set; }
        public int LossesUsing { get; set; }
        public int RechargeUsing { get; set; }
        public int IsPaid { get; set; }
        public int IsBillIncome { get; set; }
        public double Rate { get; set; }
        public Nullable<int> KeepRecharge { get; set; }
        public Nullable<int> IsPrivilege { get; set; }
        public Nullable<int> AllDiscount { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CashBaseType CashBaseType { get; set; }
    }
}
