//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearEstimate
    {
        public int Id { get; set; }
        public int DishCode { get; set; }
        public int Num { get; set; }
        public int WarnNum { get; set; }
        public int SaleNum { get; set; }
        public int LastNum { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Operator { get; set; }
        public System.DateTime EndTime { get; set; }
        public string CancleMan { get; set; }
        public Nullable<System.DateTime> CancleTime { get; set; }
        public int MidwayCancle { get; set; }
        public string Reason { get; set; }
        public System.DateTime MarkTime { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    }
}
