//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Contacts { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Addr { get; set; }
        public string Logo1 { get; set; }
        public string Logo2 { get; set; }
        public string DPName { get; set; }
        public string DPAddr { get; set; }
        public string DPParam { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string EditPerson { get; set; }
        public int Deleted { get; set; }
    }
}
