//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumeInfo
    {
        public ConsumeInfo()
        {
            this.ConsumeItem = new HashSet<ConsumeItem>();
        }
    
        public int Id { get; set; }
        public int ShiftId { get; set; }
        public string OperatorBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int TotalNum { get; set; }
        public double TotalMoney { get; set; }
    
        public virtual ICollection<ConsumeItem> ConsumeItem { get; set; }
        public virtual ShiftBill ShiftBill { get; set; }
    }
}
