//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeskDishes
    {
        public DeskDishes()
        {
            this.DeskOrder = new HashSet<DeskOrder>();
            this.TimerProject = new HashSet<TimerProject>();
        }
    
        public int DeskDishesId { get; set; }
        public string DeskNum { get; set; }
        public int OrderId { get; set; }
        public int Take { get; set; }
        public int Merged { get; set; }
        public int Locked { get; set; }
        public int Timer { get; set; }
        public int DeskStatus { get; set; }
        public int OrderStatus { get; set; }
        public int UnionCount { get; set; }
        public int PartyCount { get; set; }
        public int Turn { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CreateDesk CreateDesk { get; set; }
        public virtual ICollection<DeskOrder> DeskOrder { get; set; }
        public virtual ICollection<TimerProject> TimerProject { get; set; }
    }
}
