//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishesMenuRef
    {
        public int DishId { get; set; }
        public int MenusId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Deleted { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual DishesMenu DishesMenu { get; set; }
    }
}
