//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishPrice
    {
        public int Id { get; set; }
        public int DishId { get; set; }
        public string DishSpecification { get; set; }
        public double Price1 { get; set; }
        public double Price2 { get; set; }
        public double Price3 { get; set; }
        public double MemberPrice3 { get; set; }
        public double MemberPrice2 { get; set; }
        public double MemberPrice1 { get; set; }
    }
}
