//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitchenBill
    {
        public KitchenBill()
        {
            this.KitchenBillItem = new HashSet<KitchenBillItem>();
        }
    
        public int KitchenBillId { get; set; }
        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public int Status { get; set; }
        public int PrintType { get; set; }
        public string BillNo { get; set; }
        public int TableNo { get; set; }
        public string TableName { get; set; }
        public string Waiter { get; set; }
        public string DishServerName { get; set; }
        public int CustNum { get; set; }
    
        public virtual ICollection<KitchenBillItem> KitchenBillItem { get; set; }
    }
}
