//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitchenBillItem
    {
        public int Id { get; set; }
        public string DishCode { get; set; }
        public string DishName { get; set; }
        public int Num { get; set; }
        public double Money { get; set; }
    
        public virtual KitchenBill KitchenBill { get; set; }
    }
}
