//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public int OrdeId { get; set; }
        public string DeskNum { get; set; }
        public int Consume { get; set; }
        public int Discount { get; set; }
        public int Presented { get; set; }
        public int Service { get; set; }
        public int MinBalance { get; set; }
        public int Coupon { get; set; }
        public int Deposit { get; set; }
        public int EraseZero { get; set; }
        public int AvailableVoucher { get; set; }
        public int Receivable { get; set; }
        public int Paid { get; set; }
        public int MultiplePay { get; set; }
        public int TurnOver { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
