//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamSet
    {
        public int ParamId { get; set; }
        public string ParamName { get; set; }
        public string ParamValue { get; set; }
        public Nullable<int> ParamFlag { get; set; }
        public string ParamNote { get; set; }
    }
}
