//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayBill
    {
        public PayBill()
        {
            this.PayInfo = new HashSet<PayInfo>();
            this.PayRecord = new HashSet<PayRecord>();
        }
    
        public int Id { get; set; }
        public string PayNo { get; set; }
        public string BillNo { get; set; }
        public int TableCode { get; set; }
        public System.DateTime OpenTableTime { get; set; }
        public int Duration { get; set; }
        public string DinnerType { get; set; }
        public int CustNum { get; set; }
        public string OpenTableRemark { get; set; }
        public Nullable<System.DateTime> PrePrintTime { get; set; }
        public int PrePrintNum { get; set; }
        public double RealPay { get; set; }
        public double VoidPay { get; set; }
        public double ShouldPay { get; set; }
        public double OrgnalMoney { get; set; }
        public double DiscountMoney { get; set; }
        public double GiveMoney { get; set; }
        public double CashPay { get; set; }
        public double Free { get; set; }
        public double AccountPay { get; set; }
        public double RegisterPay { get; set; }
        public double ServiceFee { get; set; }
        public double LowConsDiffer { get; set; }
        public double CouponDeduct { get; set; }
        public double TruncationMoney { get; set; }
        public double PayType { get; set; }
        public double CashierCode { get; set; }
        public System.DateTime CheckoutTime { get; set; }
        public int Status { get; set; }
        public string SaleMan { get; set; }
        public string DiscountOperator { get; set; }
        public string RegularName { get; set; }
    
        public virtual ICollection<PayInfo> PayInfo { get; set; }
        public virtual ICollection<PayRecord> PayRecord { get; set; }
    }
}
