//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayInfo
    {
        public int Id { get; set; }
        public int PayBillId { get; set; }
        public int CheckoutType { get; set; }
        public double GetMoney { get; set; }
        public double PayMoney { get; set; }
        public double Change { get; set; }
        public double RmbChange { get; set; }
        public double Deviation { get; set; }
        public double ExchangeRate { get; set; }
        public Nullable<double> Denomination { get; set; }
        public string VoucherNo { get; set; }
        public string Reason { get; set; }
    
        public virtual PayBill PayBill { get; set; }
    }
}
