//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRecord
    {
        public int Id { get; set; }
        public int PayBillId { get; set; }
        public int PayType { get; set; }
        public double ExchangeRate { get; set; }
        public double Money { get; set; }
        public double Rmb { get; set; }
        public double Change { get; set; }
        public double RmbChange { get; set; }
        public double PayMoney { get; set; }
        public double Truncation { get; set; }
        public double OperatorId { get; set; }
        public double CreateTime { get; set; }
        public double CashRegister { get; set; }
    
        public virtual PayBill PayBill { get; set; }
    }
}
