//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public Printer()
        {
            this.BasicPrintPlan = new HashSet<BasicPrintPlan>();
        }
    
        public int PrintId { get; set; }
        public string PrinterName { get; set; }
        public int PrinterType { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Deleted { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<BasicPrintPlan> BasicPrintPlan { get; set; }
    }
}
