//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public Privilege()
        {
            this.Role = new HashSet<Role>();
        }
    
        public string PrivilegeName { get; set; }
        public string PrivilegeType { get; set; }
        public string URL { get; set; }
        public int Deleted { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string EditPerson { get; set; }
        public int PrivilegeId { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
    }
}
