//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsDish
    {
        public int PromotionsDishId { get; set; }
        public Nullable<int> DishId { get; set; }
        public int MarketTypeId { get; set; }
        public double Price { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Week_1 { get; set; }
        public int Week_2 { get; set; }
        public int Week_3 { get; set; }
        public int Week_4 { get; set; }
        public int Week_5 { get; set; }
        public int Week_6 { get; set; }
        public int Week_0 { get; set; }
        public int Status { get; set; }
        public int Usering { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual PromotionsDishDetail PromotionsDishDetail { get; set; }
    }
}
