//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsDish
    {
        public PromotionsDish()
        {
            this.PromotionsDishDetail = new HashSet<PromotionsDishDetail>();
        }
    
        public int PromotionsDishId { get; set; }
        public string TradeNo { get; set; }
        public Nullable<int> DishId { get; set; }
        public int MarketTypeId { get; set; }
        public string DishFormat { get; set; }
        public double Price { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Week_1 { get; set; }
        public int Week_2 { get; set; }
        public int Week_3 { get; set; }
        public int Week_4 { get; set; }
        public int Week_5 { get; set; }
        public int Week_6 { get; set; }
        public int Week_0 { get; set; }
        public int Status { get; set; }
        public int Usering { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual ICollection<PromotionsDishDetail> PromotionsDishDetail { get; set; }
    }
}
