//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterial
    {
        public int Id { get; set; }
        public Nullable<int> RawId { get; set; }
        public string MaterialName { get; set; }
        public string Format { get; set; }
        public string Pinying { get; set; }
        public int InGoodsUnit { get; set; }
        public int StockUnit { get; set; }
        public int InGoodsStock { get; set; }
        public int FormulaUnit { get; set; }
        public int StockFormula { get; set; }
        public double InGoodsPrice { get; set; }
        public int StockMax { get; set; }
        public int StockMin { get; set; }
        public int WriteDowns { get; set; }
        public int OrderRawAdd { get; set; }
        public Nullable<double> RawAddPrice { get; set; }
        public Nullable<int> SaleUnit { get; set; }
        public int IsWeight { get; set; }
        public int CheckDay { get; set; }
        public string Detail { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Raw Raw { get; set; }
    }
}
