//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundInfo
    {
        public RefundInfo()
        {
            this.RefundInfoItem = new HashSet<RefundInfoItem>();
        }
    
        public int RefundId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public int OperatorBy { get; set; }
        public string OperatorName { get; set; }
        public int SucceedId { get; set; }
        public string SucceedName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Remark { get; set; }
        public double TurnOnCash { get; set; }
        public int RefundNum { get; set; }
        public int RefundDishNum { get; set; }
        public double RefundMoney { get; set; }
    
        public virtual ICollection<RefundInfoItem> RefundInfoItem { get; set; }
        public virtual ShiftBill ShiftBill { get; set; }
    }
}
