//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Privilege = new HashSet<Privilege>();
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int RoleId { get; set; }
        public int OrgId { get; set; }
        public string RoleName { get; set; }
        public int Deleted { get; set; }
        public string Detail { get; set; }
        public int RoleType { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string EditPerson { get; set; }
    
        public virtual ICollection<Privilege> Privilege { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
