//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftItem
    {
        public int ShiftId { get; set; }
        public int PayType { get; set; }
        public int PayNum { get; set; }
        public double Money { get; set; }
        public double RmbMoney { get; set; }
    
        public virtual ShiftBill ShiftBill { get; set; }
    }
}
