//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int Id { get; set; }
        public string Module { get; set; }
        public string Function { get; set; }
        public string OpType { get; set; }
        public string Actor { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string Body { get; set; }
        public string ItemId { get; set; }
    }
}
