//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int id { get; set; }
        public Nullable<int> LogType { get; set; }
        public string OperFun { get; set; }
        public string Description { get; set; }
        public Nullable<int> BillType { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> OperId { get; set; }
        public Nullable<System.DateTime> OperTime { get; set; }
    }
}
