//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int id { get; set; }
        public Nullable<int> LogType { get; set; }
        public string OperFun { get; set; }
        public string Description { get; set; }
        public Nullable<int> BillType { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> OperId { get; set; }
        public Nullable<System.DateTime> OperTime { get; set; }
    }
}
