//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeoutOrder
    {
        public int TakeoutId { get; set; }
        public Nullable<int> OrderPeopleId { get; set; }
        public int OrderId { get; set; }
        public string DeliveryManNum { get; set; }
        public string Num { get; set; }
        public Nullable<int> AdvanceAmount { get; set; }
        public System.DateTime DeliverTime { get; set; }
        public System.DateTime SendTime { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public Nullable<int> Status { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual TakeoutClientInfo TakeoutClientInfo { get; set; }
    }
}
