//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerProject
    {
        public int Id { get; set; }
        public int TimerNum { get; set; }
        public Nullable<int> DeskDishesId { get; set; }
        public string DeskNum { get; set; }
        public string TimerName { get; set; }
        public System.DateTime StartTimer { get; set; }
        public Nullable<System.DateTime> PauseTimer { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual DeskDishes DeskDishes { get; set; }
    }
}
