//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Role = new HashSet<Role>();
        }
    
        public int OperatorId { get; set; }
        public int UserId { get; set; }
        public string OperatorName { get; set; }
        public string OperatorPwd { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string EditPerson { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
