//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BargainDish
    {
        public BargainDish()
        {
            this.BargainDishPrice = new HashSet<BargainDishPrice>();
        }
    
        public int Id { get; set; }
        public int DishId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Week1 { get; set; }
        public int Week2 { get; set; }
        public int Week3 { get; set; }
        public int Week4 { get; set; }
        public int Week5 { get; set; }
        public int Week6 { get; set; }
        public int Week0 { get; set; }
        public int MarketTypeId { get; set; }
        public int Enable { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Update_by { get; set; }
    
        public virtual ICollection<BargainDishPrice> BargainDishPrice { get; set; }
    }
}
