//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int UserId { get; set; }
        public int DepartmentId { get; set; }
        public string JobNo { get; set; }
        public string Name { get; set; }
        public int Sex { get; set; }
        public string Birthday { get; set; }
        public Nullable<int> Flag { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public int Deleted { get; set; }
    
        public virtual DepartmentInfo DepartmentInfo { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
