//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Utils.Logger {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IShow.ChooseDishes.Utils.Logger.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 用户[{0}]删除订单[{1}],执行操作成功 的本地化字符串。
        /// </summary>
        internal static string DEL_ORDER {
            get {
                return ResourceManager.GetString("DEL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户[{0}]登录系统 的本地化字符串。
        /// </summary>
        internal static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户[{0}]登出系统 的本地化字符串。
        /// </summary>
        internal static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员【{0}】添加角色【{1}】 的本地化字符串。
        /// </summary>
        internal static string USER_ADD_ROLE {
            get {
                return ResourceManager.GetString("USER_ADD_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员【{0}】删除用户【{1}】 的本地化字符串。
        /// </summary>
        internal static string USER_DELETE {
            get {
                return ResourceManager.GetString("USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员【{0}】禁用角色【{1}】 的本地化字符串。
        /// </summary>
        internal static string USER_DISABLE_ROLE {
            get {
                return ResourceManager.GetString("USER_DISABLE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员【{0}】启用角色【{1}】 的本地化字符串。
        /// </summary>
        internal static string USER_ENABLE_ROLE {
            get {
                return ResourceManager.GetString("USER_ENABLE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员【{0}】给用户【{1}】授权角色【{2}】 的本地化字符串。
        /// </summary>
        internal static string USER_GRANT_ROLE {
            get {
                return ResourceManager.GetString("USER_GRANT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员【{0}】新增用户【{1}】 的本地化字符串。
        /// </summary>
        internal static string USER_NEW {
            get {
                return ResourceManager.GetString("USER_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员【{0}】重置用户【{1}】密码 的本地化字符串。
        /// </summary>
        internal static string USER_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("USER_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员【{0}】收回用户【{1}】授权角色【{2}】 的本地化字符串。
        /// </summary>
        internal static string USER_REVOKE_ROLE {
            get {
                return ResourceManager.GetString("USER_REVOKE_ROLE", resourceCulture);
            }
        }
    }
}
