//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableType
    {
        public TableType()
        {
            this.Table = new HashSet<Table>();
            this.TableTypeDetail = new HashSet<TableTypeDetail>();
        }
    
        public int TableTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int PeopleMin { get; set; }
        public int PeopleMax { get; set; }
        public string Prefix { get; set; }
        public int PriceType { get; set; }
        public int ServerfreeNax { get; set; }
        public int ServerfreeModel { get; set; }
        public int ConsumerMode { get; set; }
        public string ColorType { get; set; }
        public int ServerfreeAccountType { get; set; }
        public int Rate { get; set; }
        public int ServerfreeNum { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<Table> Table { get; set; }
        public virtual ICollection<TableTypeDetail> TableTypeDetail { get; set; }
    }
}
