//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Role = new HashSet<Role>();
        }
    
        public int OperatorId { get; set; }
        public int UserId { get; set; }
        public string OperatorName { get; set; }
        public string OperatorPwd { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string EditPerson { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Role> Role { get; set; }
    }
}
