//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTypeDetail
    {
        public int TableTypeDetailId { get; set; }
        public Nullable<int> TableTypeId { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> AccountType { get; set; }
        public int ConsumerMode { get; set; }
        public Nullable<int> StartUnit { get; set; }
        public Nullable<System.DateTime> StartEnd { get; set; }
        public Nullable<double> OutMoney { get; set; }
        public Nullable<int> OutTime { get; set; }
        public Nullable<int> StartMoney { get; set; }
        public int ConsumerMoney { get; set; }
        public Nullable<int> StartGetMoneyTime { get; set; }
        public int ServerfreeNax { get; set; }
        public Nullable<int> OutTimeFree { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual TableType TableType { get; set; }
    }
}
