//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckoutSet
    {
        public int CalculationMode { get; set; }
        public int TruncationMode { get; set; }
        public int RoundMode { get; set; }
        public int InvoiceActive { get; set; }
        public int InvoiceMode { get; set; }
        public int PayFull { get; set; }
        public int PrintNum { get; set; }
        public int ShowChange { get; set; }
        public int PrintBill { get; set; }
        public int PrintWholeBill { get; set; }
        public int ChoiseTable { get; set; }
    }
}
