//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dish_cents
    {
        public Nullable<int> DishId { get; set; }
        public Nullable<int> DiancaiCents { get; set; }
        public Nullable<int> DiancaiType { get; set; }
        public Nullable<double> DiancaiCentsScale { get; set; }
        public Nullable<double> DiancaiCentsFix { get; set; }
        public Nullable<int> ServerCents { get; set; }
        public Nullable<int> ServerType { get; set; }
        public Nullable<double> ServerCentsScale { get; set; }
        public Nullable<int> ServerCentsFix { get; set; }
        public Nullable<double> SaleCents { get; set; }
        public Nullable<int> SaleType { get; set; }
        public Nullable<double> SaleCentsScale { get; set; }
        public Nullable<double> SaleCentsFix { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Dish Dish { get; set; }
    }
}
