//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class Employee
    {
        public Employee()
        {
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        [DataMember]
    public int UserId { get; set; }
        [DataMember]
    public int DepartmentId { get; set; }
        [DataMember]
    public string JobNo { get; set; }
        [DataMember]
    public string Name { get; set; }
        [DataMember]
    public int Sex { get; set; }
        [DataMember]
    public string Birthday { get; set; }
        [DataMember]
    public Nullable<int> Flag { get; set; }
        [DataMember]
    public string Mobile { get; set; }
        [DataMember]
    public string Email { get; set; }
        [DataMember]
    public System.DateTime CreateTime { get; set; }
        [DataMember]
    public string CreatePerson { get; set; }
        [DataMember]
    public Nullable<System.DateTime> EditTime { get; set; }
        [DataMember]
    public string EditPerson { get; set; }
        [DataMember]
    public int Deleted { get; set; }
    
        [DataMember]
    public virtual DepartmentInfo DepartmentInfo { get; set; }
        [DataMember]
    public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
