//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class SystemLog
    {
        [DataMember]
    public int id { get; set; }
        [DataMember]
    public Nullable<int> LogType { get; set; }
        [DataMember]
    public string OperFun { get; set; }
        [DataMember]
    public string Description { get; set; }
        [DataMember]
    public Nullable<int> BillType { get; set; }
        [DataMember]
    public string BillNo { get; set; }
        [DataMember]
    public Nullable<int> OperId { get; set; }
        [DataMember]
    public Nullable<System.DateTime> OperTime { get; set; }
    }
}
