//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class PayInfo
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int PayBillId { get; set; }
        [DataMember]
        public int CheckoutType { get; set; }
        [DataMember]
        public double GetMoney { get; set; }
        [DataMember]
        public double PayMoney { get; set; }
        [DataMember]
        public double Change { get; set; }
        [DataMember]
        public double RmbChange { get; set; }
        [DataMember]
        public double Deviation { get; set; }
        [DataMember]
        public double ExchangeRate { get; set; }
        [DataMember]
        public Nullable<double> Denomination { get; set; }
        [DataMember]
        public string VoucherNo { get; set; }
        [DataMember]
        public string Reason { get; set; }
    
        [DataMember]
        public virtual PayBill PayBill { get; set; }
    }
}
