//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundInfo
    {
        public RefundInfo()
        {
            this.RefundInfoItem = new HashSet<RefundInfoItem>();
        }
    
        public int RefundId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public int OperatorBy { get; set; }
        public string OperatorName { get; set; }
        public int SucceedId { get; set; }
        public string SucceedName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Remark { get; set; }
        public double TurnOnCash { get; set; }
        public int RefundNum { get; set; }
        public int RefundDishNum { get; set; }
        public double RefundMoney { get; set; }
    
        public virtual ICollection<RefundInfoItem> RefundInfoItem { get; set; }
        public virtual ShiftBill ShiftBill { get; set; }
    }
}
