//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderMateria = new HashSet<OrderMateria>();
            this.OrderPractice = new HashSet<OrderPractice>();
        }
    
        public int OrderItemId { get; set; }
        public int Id { get; set; }
        public string DishNum { get; set; }
        public int Price { get; set; }
        public int Num { get; set; }
        public int Quit { get; set; }
        public int Addprice { get; set; }
        public int IsPay { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public int SpecialPrice { get; set; }
        public int Weight { get; set; }
        public int Pause { get; set; }
        public int Rebate { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderMateria> OrderMateria { get; set; }
        public virtual ICollection<OrderPractice> OrderPractice { get; set; }
    }
}
