//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumeInfo
    {
        public ConsumeInfo()
        {
            this.ConsumeItem = new HashSet<ConsumeItem>();
        }
    
        public int Id { get; set; }
        public int ShiftId { get; set; }
        public string OperatorBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int TotalNum { get; set; }
        public double TotalMoney { get; set; }
    
        public virtual ICollection<ConsumeItem> ConsumeItem { get; set; }
        public virtual ShiftBill ShiftBill { get; set; }
    }
}
