//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class CheckoutSet
    {
        [DataMember]
    public int CalculationMode { get; set; }
        [DataMember]
    public int TruncationMode { get; set; }
        [DataMember]
    public int RoundMode { get; set; }
        [DataMember]
    public int InvoiceActive { get; set; }
        [DataMember]
    public int InvoiceMode { get; set; }
        [DataMember]
    public int PayFull { get; set; }
        [DataMember]
    public int PrintNum { get; set; }
        [DataMember]
    public int ShowChange { get; set; }
        [DataMember]
    public int PrintBill { get; set; }
        [DataMember]
    public int PrintWholeBill { get; set; }
        [DataMember]
    public int ChoiseTable { get; set; }
    }
}
