//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChooseDishesEntities : DbContext
    {
        public ChooseDishesEntities()
            : base("name=ChooseDishesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AreaPrintPlan> AreaPrintPlan { get; set; }
        public DbSet<BackupMoney> BackupMoney { get; set; }
        public DbSet<BargainDish> BargainDish { get; set; }
        public DbSet<BargainDishPrice> BargainDishPrice { get; set; }
        public DbSet<BasicPrintPlan> BasicPrintPlan { get; set; }
        public DbSet<Bearing> Bearing { get; set; }
        public DbSet<CashBaseType> CashBaseType { get; set; }
        public DbSet<CashType> CashType { get; set; }
        public DbSet<ChargeItem> ChargeItem { get; set; }
        public DbSet<ChargeItemDetail> ChargeItemDetail { get; set; }
        public DbSet<ChargeRule> ChargeRule { get; set; }
        public DbSet<CheckoutInfo> CheckoutInfo { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<ConsumeInfo> ConsumeInfo { get; set; }
        public DbSet<CreateDesk> CreateDesk { get; set; }
        public DbSet<DaySettlement> DaySettlement { get; set; }
        public DbSet<DbBackup> DbBackup { get; set; }
        public DbSet<DepartmentInfo> DepartmentInfo { get; set; }
        public DbSet<DeskDishes> DeskDishes { get; set; }
        public DbSet<DeskOrder> DeskOrder { get; set; }
        public DbSet<DeskOrderMateria> DeskOrderMateria { get; set; }
        public DbSet<DeskOrderPractice> DeskOrderPractice { get; set; }
        public DbSet<DischesWay> DischesWay { get; set; }
        public DbSet<DischesWayName> DischesWayName { get; set; }
        public DbSet<DiscountDetail> DiscountDetail { get; set; }
        public DbSet<DiscountProgram> DiscountProgram { get; set; }
        public DbSet<Dish> Dish { get; set; }
        public DbSet<DishDao> DishDao { get; set; }
        public DbSet<DishDetail> DishDetail { get; set; }
        public DbSet<DishesMenu> DishesMenu { get; set; }
        public DbSet<DishFinance> DishFinance { get; set; }
        public DbSet<DishPrice> DishPrice { get; set; }
        public DbSet<DishPrint> DishPrint { get; set; }
        public DbSet<DishType> DishType { get; set; }
        public DbSet<DishUnit> DishUnit { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<GiveInvoice> GiveInvoice { get; set; }
        public DbSet<KitchenBill> KitchenBill { get; set; }
        public DbSet<KitchenBillFormat> KitchenBillFormat { get; set; }
        public DbSet<KitchenPrintSet> KitchenPrintSet { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<MarketType> MarketType { get; set; }
        public DbSet<MaterialPrint> MaterialPrint { get; set; }
        public DbSet<MemberRecharge> MemberRecharge { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderItem> OrderItem { get; set; }
        public DbSet<ParamSet> ParamSet { get; set; }
        public DbSet<PayBill> PayBill { get; set; }
        public DbSet<PayInfo> PayInfo { get; set; }
        public DbSet<PayRecord> PayRecord { get; set; }
        public DbSet<Printer> Printer { get; set; }
        public DbSet<PrintSet> PrintSet { get; set; }
        public DbSet<Privilege> Privilege { get; set; }
        public DbSet<PromotionsDish> PromotionsDish { get; set; }
        public DbSet<PromotionsDishDetail> PromotionsDishDetail { get; set; }
        public DbSet<Raw> Raw { get; set; }
        public DbSet<RawMaterial> RawMaterial { get; set; }
        public DbSet<RawUnit> RawUnit { get; set; }
        public DbSet<RechargeItem> RechargeItem { get; set; }
        public DbSet<RefundInfo> RefundInfo { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<ShiftBill> ShiftBill { get; set; }
        public DbSet<SystemLog> SystemLog { get; set; }
        public DbSet<Table> Table { get; set; }
        public DbSet<TableType> TableType { get; set; }
        public DbSet<TableTypeDetail> TableTypeDetail { get; set; }
        public DbSet<TakeoutClientInfo> TakeoutClientInfo { get; set; }
        public DbSet<TakeoutOrder> TakeoutOrder { get; set; }
        public DbSet<TimerProject> TimerProject { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<CheckoutIinfoItem> CheckoutIinfoItem { get; set; }
        public DbSet<CheckoutSet> CheckoutSet { get; set; }
        public DbSet<ClearEstimate> ClearEstimate { get; set; }
        public DbSet<ConsumeItem> ConsumeItem { get; set; }
        public DbSet<DischesWayRef> DischesWayRef { get; set; }
        public DbSet<dish_cents> dish_cents { get; set; }
        public DbSet<DishesMenuRef> DishesMenuRef { get; set; }
        public DbSet<KitchenBillItem> KitchenBillItem { get; set; }
        public DbSet<OrderMateria> OrderMateria { get; set; }
        public DbSet<OrderPractice> OrderPractice { get; set; }
        public DbSet<RefundInfoItem> RefundInfoItem { get; set; }
        public DbSet<ShiftItem> ShiftItem { get; set; }
    }
}
