//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class Company
    {
        public Company()
        {
            this.DepartmentInfo = new HashSet<DepartmentInfo>();
        }
    
        [DataMember]
    public int CompanyId { get; set; }
        [DataMember]
    public string CompanyName { get; set; }
        [DataMember]
    public string Contacts { get; set; }
        [DataMember]
    public string Phone { get; set; }
        [DataMember]
    public string Mobile { get; set; }
        [DataMember]
    public string Email { get; set; }
        [DataMember]
    public string Addr { get; set; }
        [DataMember]
    public string Logo1 { get; set; }
        [DataMember]
    public string Logo2 { get; set; }
        [DataMember]
    public string DPName { get; set; }
        [DataMember]
    public string DPAddr { get; set; }
        [DataMember]
    public string DPParam { get; set; }
        [DataMember]
    public System.DateTime CreateTime { get; set; }
        [DataMember]
    public string CreatePerson { get; set; }
        [DataMember]
    public Nullable<System.DateTime> EditTime { get; set; }
        [DataMember]
    public string EditPerson { get; set; }
        [DataMember]
    public int Deleted { get; set; }
    
        [DataMember]
    public virtual ICollection<DepartmentInfo> DepartmentInfo { get; set; }
    }
}
