//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class Dish
    {
        public Dish()
        {
            this.DischesWayRef = new HashSet<DischesWayRef>();
            this.dish_cents = new HashSet<dish_cents>();
            this.DishDao = new HashSet<DishDao>();
            this.DishesMenuRef = new HashSet<DishesMenuRef>();
            this.PromotionsDish = new HashSet<PromotionsDish>();
        }
    
        [DataMember]
    public int DishId { get; set; }
        [DataMember]
    public int DishTypeId { get; set; }
        [DataMember]
    public Nullable<int> DishUnitId { get; set; }
        [DataMember]
    public Nullable<int> DishFinanceId { get; set; }
        [DataMember]
    public string Code { get; set; }
        [DataMember]
    public string DishName { get; set; }
        [DataMember]
    public string PingYing { get; set; }
        [DataMember]
    public string AidNumber { get; set; }
        [DataMember]
    public string EnglishName { get; set; }
        [DataMember]
    public string DishFormat { get; set; }
        [DataMember]
    public int WeightConfirm { get; set; }
        [DataMember]
    public int LowConsumerConfirm { get; set; }
        [DataMember]
    public int ServerfreeConsumer { get; set; }
        [DataMember]
    public int SanpConfirm { get; set; }
        [DataMember]
    public int IsStop { get; set; }
        [DataMember]
    public int DiscountConfirm { get; set; }
        [DataMember]
    public int PriceTimeConfirm { get; set; }
        [DataMember]
    public int PackagesConfirm { get; set; }
        [DataMember]
    public int PosConfirm { get; set; }
        [DataMember]
    public int FoodFight { get; set; }
        [DataMember]
    public int LineConfirm { get; set; }
        [DataMember]
    public int DischesType { get; set; }
        [DataMember]
    public string Detail { get; set; }
        [DataMember]
    public string Img { get; set; }
        [DataMember]
    public Nullable<int> KitchenType { get; set; }
        [DataMember]
    public Nullable<int> PublisherType { get; set; }
        [DataMember]
    public System.DateTime CreateDatetime { get; set; }
        [DataMember]
    public int CreateBy { get; set; }
        [DataMember]
    public int Deleted { get; set; }
        [DataMember]
    public int Status { get; set; }
        [DataMember]
    public Nullable<System.DateTime> UpdateDatetime { get; set; }
        [DataMember]
    public Nullable<int> UpdateBy { get; set; }
    
        [DataMember]
    public virtual ICollection<DischesWayRef> DischesWayRef { get; set; }
        [DataMember]
    public virtual ICollection<dish_cents> dish_cents { get; set; }
        [DataMember]
    public virtual DishFinance DishFinance { get; set; }
        [DataMember]
    public virtual DishType DishType { get; set; }
        [DataMember]
    public virtual DishUnit DishUnit { get; set; }
        [DataMember]
    public virtual ICollection<DishDao> DishDao { get; set; }
        [DataMember]
    public virtual ICollection<DishesMenuRef> DishesMenuRef { get; set; }
        [DataMember]
    public virtual ICollection<PromotionsDish> PromotionsDish { get; set; }
    }
}
