//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class PrintSet
    {
        public PrintSet()
        {
            this.BasicPrintPlan = new HashSet<BasicPrintPlan>();
        }
    
        [DataMember]
    public int Id { get; set; }
        [DataMember]
    public int PrintName { get; set; }
        [DataMember]
    public int TicketType { get; set; }
        [DataMember]
    public int BlankRow { get; set; }
        [DataMember]
    public int PrintNum { get; set; }
        [DataMember]
    public int FormatId { get; set; }
        [DataMember]
    public int CutType { get; set; }
        [DataMember]
    public int PrintRate { get; set; }
        [DataMember]
    public string CreateBy { get; set; }
        [DataMember]
    public System.DateTime CreateTime { get; set; }
        [DataMember]
    public int Deleted { get; set; }
        [DataMember]
    public System.DateTime UpdateTime { get; set; }
        [DataMember]
    public string UpdateBy { get; set; }
        [DataMember]
    public int Status { get; set; }
    
        [DataMember]
    public virtual ICollection<BasicPrintPlan> BasicPrintPlan { get; set; }
        [DataMember]
    public virtual KitchenBillFormat KitchenBillFormat { get; set; }
    }
}
