//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class Privilege
    {
        public Privilege()
        {
            this.Role = new HashSet<Role>();
        }
    
        [DataMember]
    public string PrivilegeName { get; set; }
        [DataMember]
    public string PrivilegeType { get; set; }
        [DataMember]
    public string URL { get; set; }
        [DataMember]
    public int Deleted { get; set; }
        [DataMember]
    public string Remark { get; set; }
        [DataMember]
    public System.DateTime CreateTime { get; set; }
        [DataMember]
    public string CreatePerson { get; set; }
        [DataMember]
    public Nullable<System.DateTime> EditTime { get; set; }
        [DataMember]
    public string EditPerson { get; set; }
        [DataMember]
    public int PrivilegeId { get; set; }
    
        [DataMember]
    public virtual ICollection<Role> Role { get; set; }
    }
}
