//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class RawMaterial
    {
        [DataMember]
    public int Id { get; set; }
        [DataMember]
    public Nullable<int> RawId { get; set; }
        [DataMember]
    public string MaterialName { get; set; }
        [DataMember]
    public string Format { get; set; }
        [DataMember]
    public string Pinying { get; set; }
        [DataMember]
    public int InGoodsUnit { get; set; }
        [DataMember]
    public int StockUnit { get; set; }
        [DataMember]
    public int InGoodsStock { get; set; }
        [DataMember]
    public int FormulaUnit { get; set; }
        [DataMember]
    public int StockFormula { get; set; }
        [DataMember]
    public double InGoodsPrice { get; set; }
        [DataMember]
    public int StockMax { get; set; }
        [DataMember]
    public int StockMin { get; set; }
        [DataMember]
    public int WriteDowns { get; set; }
        [DataMember]
    public int OrderRawAdd { get; set; }
        [DataMember]
    public Nullable<double> RawAddPrice { get; set; }
        [DataMember]
    public Nullable<int> SaleUnit { get; set; }
        [DataMember]
    public int IsWeight { get; set; }
        [DataMember]
    public int CheckDay { get; set; }
        [DataMember]
    public string Detail { get; set; }
        [DataMember]
    public System.DateTime CreateDatetime { get; set; }
        [DataMember]
    public int CreateBy { get; set; }
        [DataMember]
    public int Deleted { get; set; }
        [DataMember]
    public int Status { get; set; }
        [DataMember]
    public Nullable<System.DateTime> UpdateDatetime { get; set; }
        [DataMember]
    public Nullable<int> UpdateBy { get; set; }
    
        [DataMember]
    public virtual Raw Raw { get; set; }
    }
}
