//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class TableType
    {
        public TableType()
        {
            this.Table = new HashSet<Table>();
            this.TableTypeDetail = new HashSet<TableTypeDetail>();
        }
    
        [DataMember]
    public int TableTypeId { get; set; }
        [DataMember]
    public string Code { get; set; }
        [DataMember]
    public string Name { get; set; }
        [DataMember]
    public int PeopleMin { get; set; }
        [DataMember]
    public int PeopleMax { get; set; }
        [DataMember]
    public string Prefix { get; set; }
        [DataMember]
    public int PriceType { get; set; }
        [DataMember]
    public int ServerfreeNax { get; set; }
        [DataMember]
    public int ServerfreeModel { get; set; }
        [DataMember]
    public int ConsumerMode { get; set; }
        [DataMember]
    public string ColorType { get; set; }
        [DataMember]
    public int ServerfreeAccountType { get; set; }
        [DataMember]
    public int Rate { get; set; }
        [DataMember]
    public int ServerfreeNum { get; set; }
        [DataMember]
    public System.DateTime CreateDatetime { get; set; }
        [DataMember]
    public int CreateBy { get; set; }
        [DataMember]
    public int Deleted { get; set; }
        [DataMember]
    public int Status { get; set; }
        [DataMember]
    public Nullable<System.DateTime> UpdateDatetime { get; set; }
        [DataMember]
    public Nullable<int> UpdateBy { get; set; }
    
        [DataMember]
    public virtual ICollection<Table> Table { get; set; }
        [DataMember]
    public virtual ICollection<TableTypeDetail> TableTypeDetail { get; set; }
    }
}
