//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class GiveInvoice
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string BillNo { get; set; }
        [DataMember]
        public Nullable<int> ContentType { get; set; }
        [DataMember]
        public Nullable<int> GiftId { get; set; }
        [DataMember]
        public string GiftName { get; set; }
        [DataMember]
        public Nullable<double> OrgnalMoney { get; set; }
        [DataMember]
        public Nullable<double> RealPay { get; set; }
        [DataMember]
        public Nullable<double> RealReleaseInvoice { get; set; }
        [DataMember]
        public string Remark { get; set; }
        [DataMember]
        public int OperatorId { get; set; }
        [DataMember]
        public string OperatorName { get; set; }
        [DataMember]
        public System.DateTime CreateTime { get; set; }
    }
}
