//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="www.IShow.com", ConfigurationName="IChooseDishesDataService", CallbackContract=typeof(IChooseDishesDataServiceCallback))]
public interface IChooseDishesDataService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="www.IShow.com/IChooseDishesDataService/Login", ReplyAction="www.IShow.com/IChooseDishesDataService/LoginResponse")]
    bool Login(string name, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="www.IShow.com/IChooseDishesDataService/Login", ReplyAction="www.IShow.com/IChooseDishesDataService/LoginResponse")]
    System.Threading.Tasks.Task<bool> LoginAsync(string name, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="www.IShow.com/IChooseDishesDataService/GetAllName", ReplyAction="www.IShow.com/IChooseDishesDataService/GetAllNameResponse")]
    string[] GetAllName();
    
    [System.ServiceModel.OperationContractAttribute(Action="www.IShow.com/IChooseDishesDataService/GetAllName", ReplyAction="www.IShow.com/IChooseDishesDataService/GetAllNameResponse")]
    System.Threading.Tasks.Task<string[]> GetAllNameAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChooseDishesDataServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(Action="www.IShow.com/IChooseDishesDataService/Changed", ReplyAction="www.IShow.com/IChooseDishesDataService/ChangedResponse")]
    void Changed();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChooseDishesDataServiceChannel : IChooseDishesDataService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ChooseDishesDataServiceClient : System.ServiceModel.DuplexClientBase<IChooseDishesDataService>, IChooseDishesDataService
{
    
    public ChooseDishesDataServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public ChooseDishesDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public ChooseDishesDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChooseDishesDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChooseDishesDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public bool Login(string name, string password)
    {
        return base.Channel.Login(name, password);
    }
    
    public System.Threading.Tasks.Task<bool> LoginAsync(string name, string password)
    {
        return base.Channel.LoginAsync(name, password);
    }
    
    public string[] GetAllName()
    {
        return base.Channel.GetAllName();
    }
    
    public System.Threading.Tasks.Task<string[]> GetAllNameAsync()
    {
        return base.Channel.GetAllNameAsync();
    }
}
