//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class BasicPrintPlan
    {
        public BasicPrintPlan()
        {
            this.AreaPrintPlan = new HashSet<AreaPrintPlan>();
            this.DishPrint = new HashSet<DishPrint>();
            this.MaterialPrint = new HashSet<MaterialPrint>();
        }
    
        [DataMember]
        public int PlanId { get; set; }
        [DataMember]
        public string PlanName { get; set; }
        [DataMember]
        public int PrintSetId { get; set; }
        [DataMember]
        public int PrinterId { get; set; }
        [DataMember]
        public string CreateBy { get; set; }
        [DataMember]
        public System.DateTime CreateTime { get; set; }
        [DataMember]
        public int Deleted { get; set; }
        [DataMember]
        public Nullable<System.DateTime> UpdateTime { get; set; }
        [DataMember]
        public string UpdateBy { get; set; }
        [DataMember]
        public int Status { get; set; }
    
        [DataMember]
        public virtual ICollection<AreaPrintPlan> AreaPrintPlan { get; set; }
        [DataMember]
        public virtual Printer Printer { get; set; }
        [DataMember]
        public virtual PrintSet PrintSet { get; set; }
        [DataMember]
        public virtual ICollection<DishPrint> DishPrint { get; set; }
        [DataMember]
        public virtual ICollection<MaterialPrint> MaterialPrint { get; set; }
    }
}
