//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class DeskDishes
    {
        public DeskDishes()
        {
            this.DeskOrder = new HashSet<DeskOrder>();
            this.TimerProject = new HashSet<TimerProject>();
        }
    
        [DataMember]
        public int DeskDishesId { get; set; }
        [DataMember]
        public string DeskNum { get; set; }
        [DataMember]
        public int OrderId { get; set; }
        [DataMember]
        public int Take { get; set; }
        [DataMember]
        public int Merged { get; set; }
        [DataMember]
        public int Locked { get; set; }
        [DataMember]
        public int Timer { get; set; }
        [DataMember]
        public int DeskStatus { get; set; }
        [DataMember]
        public int OrderStatus { get; set; }
        [DataMember]
        public int UnionCount { get; set; }
        [DataMember]
        public int PartyCount { get; set; }
        [DataMember]
        public int Turn { get; set; }
        [DataMember]
        public System.DateTime CreateDatetime { get; set; }
        [DataMember]
        public int CreateBy { get; set; }
        [DataMember]
        public int Deleted { get; set; }
        [DataMember]
        public int Status { get; set; }
        [DataMember]
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        [DataMember]
        public Nullable<int> UpdateBy { get; set; }
    
        [DataMember]
        public virtual CreateDesk CreateDesk { get; set; }
        [DataMember]
        public virtual ICollection<DeskOrder> DeskOrder { get; set; }
        [DataMember]
        public virtual ICollection<TimerProject> TimerProject { get; set; }
    }
}
