//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class DishPrice
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int DishId { get; set; }
        [DataMember]
        public string DishSpecification { get; set; }
        [DataMember]
        public double Price1 { get; set; }
        [DataMember]
        public double Price2 { get; set; }
        [DataMember]
        public double Price3 { get; set; }
        [DataMember]
        public double MemberPrice3 { get; set; }
        [DataMember]
        public double MemberPrice2 { get; set; }
        [DataMember]
        public double MemberPrice1 { get; set; }
    }
}
