//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class KitchenBill
    {
        public KitchenBill()
        {
            this.KitchenBillItem = new HashSet<KitchenBillItem>();
        }
    
        [DataMember]
        public int KitchenBillId { get; set; }
        [DataMember]
        public int PlanId { get; set; }
        [DataMember]
        public string PlanName { get; set; }
        [DataMember]
        public int Status { get; set; }
        [DataMember]
        public int PrintType { get; set; }
        [DataMember]
        public string BillNo { get; set; }
        [DataMember]
        public int TableNo { get; set; }
        [DataMember]
        public string TableName { get; set; }
        [DataMember]
        public string Waiter { get; set; }
        [DataMember]
        public string DishServerName { get; set; }
        [DataMember]
        public int CustNum { get; set; }
    
        [DataMember]
        public virtual ICollection<KitchenBillItem> KitchenBillItem { get; set; }
    }
}
