//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class KitchenBillFormat
    {
        public KitchenBillFormat()
        {
            this.PrintSet = new HashSet<PrintSet>();
        }
    
        [DataMember]
        public int FormatId { get; set; }
        [DataMember]
        public int PaperType { get; set; }
        [DataMember]
        public int PaperWidth { get; set; }
        [DataMember]
        public int BillType { get; set; }
        [DataMember]
        public int TableCode { get; set; }
        [DataMember]
        public int TableFont { get; set; }
        [DataMember]
        public int BillNo { get; set; }
        [DataMember]
        public int CustNum { get; set; }
        [DataMember]
        public int HeadFont { get; set; }
        [DataMember]
        public int WaiterName { get; set; }
        [DataMember]
        public int DishServerName { get; set; }
        [DataMember]
        public int OpenTableRemark { get; set; }
        [DataMember]
        public int OrdeTtime { get; set; }
        [DataMember]
        public int OrderRemark { get; set; }
        [DataMember]
        public int OrderRemarkFont { get; set; }
        [DataMember]
        public int DetailFont { get; set; }
        [DataMember]
        public int DishNum { get; set; }
        [DataMember]
        public int DishNumFormat { get; set; }
        [DataMember]
        public int DishUnit { get; set; }
        [DataMember]
        public int DishPrice { get; set; }
        [DataMember]
        public int DishPriceFormat { get; set; }
        [DataMember]
        public int EndFont { get; set; }
        [DataMember]
        public int TotalNum { get; set; }
        [DataMember]
        public int TotalNumFormat { get; set; }
        [DataMember]
        public int TotalMoney { get; set; }
        [DataMember]
        public int TotalMoneyFormat { get; set; }
        [DataMember]
        public int PrintTime { get; set; }
        [DataMember]
        public string CreateBy { get; set; }
        [DataMember]
        public System.DateTime Createatetime { get; set; }
        [DataMember]
        public int Deleted { get; set; }
        [DataMember]
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        [DataMember]
        public string UpdateBy { get; set; }
        [DataMember]
        public int Status { get; set; }
    
        [DataMember]
        public virtual ICollection<PrintSet> PrintSet { get; set; }
    }
}
