//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class PayBill
    {
        public PayBill()
        {
            this.PayInfo = new HashSet<PayInfo>();
            this.PayRecord = new HashSet<PayRecord>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string PayNo { get; set; }
        [DataMember]
        public string BillNo { get; set; }
        [DataMember]
        public int TableCode { get; set; }
        [DataMember]
        public System.DateTime OpenTableTime { get; set; }
        [DataMember]
        public int Duration { get; set; }
        [DataMember]
        public string DinnerType { get; set; }
        [DataMember]
        public int CustNum { get; set; }
        [DataMember]
        public string OpenTableRemark { get; set; }
        [DataMember]
        public Nullable<System.DateTime> PrePrintTime { get; set; }
        [DataMember]
        public int PrePrintNum { get; set; }
        [DataMember]
        public double RealPay { get; set; }
        [DataMember]
        public double VoidPay { get; set; }
        [DataMember]
        public double ShouldPay { get; set; }
        [DataMember]
        public double OrgnalMoney { get; set; }
        [DataMember]
        public double DiscountMoney { get; set; }
        [DataMember]
        public double GiveMoney { get; set; }
        [DataMember]
        public double CashPay { get; set; }
        [DataMember]
        public double Free { get; set; }
        [DataMember]
        public double AccountPay { get; set; }
        [DataMember]
        public double RegisterPay { get; set; }
        [DataMember]
        public double ServiceFee { get; set; }
        [DataMember]
        public double LowConsDiffer { get; set; }
        [DataMember]
        public double CouponDeduct { get; set; }
        [DataMember]
        public double TruncationMoney { get; set; }
        [DataMember]
        public double PayType { get; set; }
        [DataMember]
        public double CashierCode { get; set; }
        [DataMember]
        public System.DateTime CheckoutTime { get; set; }
        [DataMember]
        public int Status { get; set; }
        [DataMember]
        public string SaleMan { get; set; }
        [DataMember]
        public string DiscountOperator { get; set; }
        [DataMember]
        public string RegularName { get; set; }
    
        [DataMember]
        public virtual ICollection<PayInfo> PayInfo { get; set; }
        [DataMember]
        public virtual ICollection<PayRecord> PayRecord { get; set; }
    }
}
