//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class PromotionsDish
    {
        [DataMember]
        public int PromotionsDishId { get; set; }
        [DataMember]
        public Nullable<int> DishId { get; set; }
        [DataMember]
        public int MarketTypeId { get; set; }
        [DataMember]
        public double Price { get; set; }
        [DataMember]
        public System.DateTime StartTime { get; set; }
        [DataMember]
        public System.DateTime EndTime { get; set; }
        [DataMember]
        public System.DateTime StartDate { get; set; }
        [DataMember]
        public System.DateTime EndDate { get; set; }
        [DataMember]
        public int Week_1 { get; set; }
        [DataMember]
        public int Week_2 { get; set; }
        [DataMember]
        public int Week_3 { get; set; }
        [DataMember]
        public int Week_4 { get; set; }
        [DataMember]
        public int Week_5 { get; set; }
        [DataMember]
        public int Week_6 { get; set; }
        [DataMember]
        public int Week_0 { get; set; }
        [DataMember]
        public int Status { get; set; }
        [DataMember]
        public int Usering { get; set; }
        [DataMember]
        public System.DateTime CreateDatetime { get; set; }
        [DataMember]
        public int CreateBy { get; set; }
        [DataMember]
        public int Deleted { get; set; }
        [DataMember]
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        [DataMember]
        public Nullable<int> UpdateBy { get; set; }
    
        [DataMember]
        public virtual Dish Dish { get; set; }
        [DataMember]
        public virtual PromotionsDishDetail PromotionsDishDetail { get; set; }
    }
}
