//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class RechargeItem
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int RechargeId { get; set; }
        [DataMember]
        public int PayTypeId { get; set; }
        [DataMember]
        public int PayTypeName { get; set; }
        [DataMember]
        public int PayNum { get; set; }
        [DataMember]
        public double RechargeMoney { get; set; }
        [DataMember]
        public double PayMoney { get; set; }
    
        [DataMember]
        public virtual MemberRecharge MemberRecharge { get; set; }
    }
}
