//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class TakeoutClientInfo
    {
        public TakeoutClientInfo()
        {
            this.TakeoutOrder = new HashSet<TakeoutOrder>();
        }
    
        [DataMember]
        public int OrderPeopleId { get; set; }
        [DataMember]
        public string Order_people { get; set; }
        [DataMember]
        public string Telephone { get; set; }
        [DataMember]
        public string Mobile { get; set; }
        [DataMember]
        public string Address { get; set; }
        [DataMember]
        public System.DateTime Create_datetime { get; set; }
        [DataMember]
        public int Create_by { get; set; }
        [DataMember]
        public int Deleted { get; set; }
        [DataMember]
        public int Status { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Update_datetime { get; set; }
        [DataMember]
        public Nullable<int> Update_by { get; set; }
    
        [DataMember]
        public virtual ICollection<TakeoutOrder> TakeoutOrder { get; set; }
    }
}
