//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaPrintPlan
    {
        public AreaPrintPlan()
        {
            this.DishPrint = new HashSet<DishPrint>();
            this.MaterialPrint = new HashSet<MaterialPrint>();
        }
    
        public int AreaPlanId { get; set; }
        public string PlanName { get; set; }
        public int AreaId { get; set; }
        public int BasicPlanId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public int Status { get; set; }
    
        public virtual BasicPrintPlan BasicPrintPlan { get; set; }
        public virtual ICollection<DishPrint> DishPrint { get; set; }
        public virtual ICollection<MaterialPrint> MaterialPrint { get; set; }
    }
}
