//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicPrintPlan
    {
        public BasicPrintPlan()
        {
            this.AreaPrintPlan = new HashSet<AreaPrintPlan>();
            this.DishPrint = new HashSet<DishPrint>();
            this.MaterialPrint = new HashSet<MaterialPrint>();
        }
    
        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public int PrintSetId { get; set; }
        public int PrinterId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<AreaPrintPlan> AreaPrintPlan { get; set; }
        public virtual Printer Printer { get; set; }
        public virtual PrintSet PrintSet { get; set; }
        public virtual ICollection<DishPrint> DishPrint { get; set; }
        public virtual ICollection<MaterialPrint> MaterialPrint { get; set; }
    }
}
