//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeRule
    {
        public ChargeRule()
        {
            this.ChargeItemDetail = new HashSet<ChargeItemDetail>();
        }
    
        public int Id { get; set; }
        public int ItemId { get; set; }
        public string Rule { get; set; }
    
        public virtual ChargeItem ChargeItem { get; set; }
        public virtual ICollection<ChargeItemDetail> ChargeItemDetail { get; set; }
    }
}
