//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckoutSet
    {
        public int CalculationMode { get; set; }
        public int TruncationMode { get; set; }
        public int RoundMode { get; set; }
        public int InvoiceActive { get; set; }
        public int InvoiceMode { get; set; }
        public int PayFull { get; set; }
        public int PrintNum { get; set; }
        public int ShowChange { get; set; }
        public int PrintBill { get; set; }
        public int PrintWholeBill { get; set; }
        public int ChoiseTable { get; set; }
    }
}
