//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string FormatType { get; set; }
        public string Domain { get; set; }
        public int Disabled { get; set; }
        public int Deleted { get; set; }
        public string Description { get; set; }
    }
}
