//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbBackup
    {
        public int BackupsId { get; set; }
        public string BackUrl { get; set; }
        public Nullable<System.DateTime> BackDate { get; set; }
        public string BackName { get; set; }
        public Nullable<System.DateTime> BackPlanDate { get; set; }
    }
}
