//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeskOrder
    {
        public DeskOrder()
        {
            this.DeskOrderMateria = new HashSet<DeskOrderMateria>();
            this.DeskOrderPractice = new HashSet<DeskOrderPractice>();
        }
    
        public int DeskOrderId { get; set; }
        public int DeskDishesId { get; set; }
        public string DishNum { get; set; }
        public int Price { get; set; }
        public int Num { get; set; }
        public int Quit { get; set; }
        public int SpecialPrice { get; set; }
        public int Weight { get; set; }
        public int Pause { get; set; }
        public int Urge { get; set; }
        public int Rebate { get; set; }
        public Nullable<int> Discount { get; set; }
        public int Single_note { get; set; }
        public int Temporary_menu { get; set; }
        public Nullable<int> TemporaryMenuNum { get; set; }
        public int ClearDish { get; set; }
        public int IsDshes { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual DeskDishes DeskDishes { get; set; }
        public virtual ICollection<DeskOrderMateria> DeskOrderMateria { get; set; }
        public virtual ICollection<DeskOrderPractice> DeskOrderPractice { get; set; }
    }
}
