//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        public Function()
        {
            this.RoleRefFunction = new HashSet<RoleRefFunction>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ModuleId { get; set; }
        public string Description { get; set; }
        public int Disabled { get; set; }
        public int Deleted { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ICollection<RoleRefFunction> RoleRefFunction { get; set; }
    }
}
