//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitchenBill
    {
        public KitchenBill()
        {
            this.KitchenBillItem = new HashSet<KitchenBillItem>();
        }
    
        public int KitchenBillId { get; set; }
        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public int Status { get; set; }
        public int PrintType { get; set; }
        public string BillNo { get; set; }
        public int TableNo { get; set; }
        public string TableName { get; set; }
        public string Waiter { get; set; }
        public string DishServerName { get; set; }
        public int CustNum { get; set; }
    
        public virtual ICollection<KitchenBillItem> KitchenBillItem { get; set; }
    }
}
