//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitchenPrintSet
    {
        public int Id { get; set; }
        public string ServiceIP { get; set; }
        public int AutoBoot { get; set; }
        public int RefreshPeriod { get; set; }
        public int ServerAutoStart { get; set; }
        public int StartTime { get; set; }
        public int LimitPrint { get; set; }
        public int LimitTime { get; set; }
    }
}
