//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialPrint
    {
        public int Id { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public int Type { get; set; }
        public int PlanId { get; set; }
        public int AreaPlanId { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime Createtime { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public int Status { get; set; }
    
        public virtual AreaPrintPlan AreaPrintPlan { get; set; }
        public virtual BasicPrintPlan BasicPrintPlan { get; set; }
    }
}
