//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRecharge
    {
        public MemberRecharge()
        {
            this.RechargeItem = new HashSet<RechargeItem>();
        }
    
        public int RechargeId { get; set; }
        public int ShiftId { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int RechargeNum { get; set; }
        public double RechargeMoney { get; set; }
        public double PayMoney { get; set; }
    
        public virtual ShiftBill ShiftBill { get; set; }
        public virtual ICollection<RechargeItem> RechargeItem { get; set; }
    }
}
