//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderMateria = new HashSet<OrderMateria>();
            this.OrderPractice = new HashSet<OrderPractice>();
        }
    
        public int OrderItemId { get; set; }
        public string OrderId { get; set; }
        public string DishNum { get; set; }
        public int Price { get; set; }
        public int Num { get; set; }
        public int Quit { get; set; }
        public int Addprice { get; set; }
        public int IsPay { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public int SpecialPrice { get; set; }
        public int Weight { get; set; }
        public int Pause { get; set; }
        public int Rebate { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderMateria> OrderMateria { get; set; }
        public virtual ICollection<OrderPractice> OrderPractice { get; set; }
    }
}
