//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRecord
    {
        public int Id { get; set; }
        public int PayBillId { get; set; }
        public int PayType { get; set; }
        public double ExchangeRate { get; set; }
        public double Money { get; set; }
        public double Rmb { get; set; }
        public double Change { get; set; }
        public double RmbChange { get; set; }
        public double PayMoney { get; set; }
        public double Truncation { get; set; }
        public double OperatorId { get; set; }
        public double CreateTime { get; set; }
        public double CashRegister { get; set; }
    
        public virtual PayBill PayBill { get; set; }
    }
}
