//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundInfoItem
    {
        public int RefundId { get; set; }
        public string DishCode { get; set; }
        public string DishName { get; set; }
        public int RefundDishNum { get; set; }
        public double RefundMoney { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual RefundInfo RefundInfo { get; set; }
    }
}
