//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.ChooseDishes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashType
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CashBaseTypeId { get; set; }
        public int UseingKeys { get; set; }
        public string Keys { get; set; }
        public int IsScore { get; set; }
        public int ReceptionUseing { get; set; }
        public int SupplierUsing { get; set; }
        public int LossesUsing { get; set; }
        public int RechargeUsing { get; set; }
        public int IsPaid { get; set; }
        public int IsBillIncome { get; set; }
        public double Rate { get; set; }
        public Nullable<int> KeepRecharge { get; set; }
        public Nullable<int> IsPrivilege { get; set; }
        public Nullable<int> AllDiscount { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int CreateBy { get; set; }
        public int Deleted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CashBaseType CashBaseType { get; set; }
    }
}
