//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IShow.Service.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(Namespace = "www.IShow.com", IsReference = true)]
    public partial class ShiftBill
    {
        public ShiftBill()
        {
            this.CheckoutInfo = new HashSet<CheckoutInfo>();
            this.ConsumeInfo = new HashSet<ConsumeInfo>();
            this.MemberRecharge = new HashSet<MemberRecharge>();
            this.RefundInfo = new HashSet<RefundInfo>();
            this.ShiftItem = new HashSet<ShiftItem>();
        }
    
        [DataMember]
    public int ShiftId { get; set; }
        [DataMember]
    public string ShiftNo { get; set; }
        [DataMember]
    public System.DateTime StartTime { get; set; }
        [DataMember]
    public System.DateTime EndTime { get; set; }
        [DataMember]
    public string OperatorBy { get; set; }
        [DataMember]
    public string SucceedTo { get; set; }
        [DataMember]
    public double BackupMoney { get; set; }
        [DataMember]
    public double ShuldTurnOnMoney { get; set; }
        [DataMember]
    public double TurnOnCash { get; set; }
        [DataMember]
    public double Cdk { get; set; }
        [DataMember]
    public string Remark { get; set; }
        [DataMember]
    public int PayNum { get; set; }
        [DataMember]
    public double RmbPayMoney { get; set; }
        [DataMember]
    public double OperatingIncome { get; set; }
        [DataMember]
    public int TableNum { get; set; }
        [DataMember]
    public int CustNum { get; set; }
        [DataMember]
    public int BillNum { get; set; }
        [DataMember]
    public double ConsumeMoney { get; set; }
        [DataMember]
    public double DiscountMoney { get; set; }
        [DataMember]
    public double GiveMoney { get; set; }
        [DataMember]
    public double TruncationMoney { get; set; }
        [DataMember]
    public double Dxc { get; set; }
        [DataMember]
    public double FreeMoney { get; set; }
        [DataMember]
    public double ServeMoney { get; set; }
        [DataMember]
    public double ShouldPayTotal { get; set; }
        [DataMember]
    public double BillAverageConsume { get; set; }
        [DataMember]
    public double Djyj { get; set; }
        [DataMember]
    public double CustlAverageConsume { get; set; }
        [DataMember]
    public double Rjyj { get; set; }
        [DataMember]
    public int ShouldReleaseInvoice { get; set; }
        [DataMember]
    public int RealReleaseInvoice { get; set; }
        [DataMember]
    public double Deposit { get; set; }
        [DataMember]
    public double ReturnDeposit { get; set; }
    
        [DataMember]
    public virtual ICollection<CheckoutInfo> CheckoutInfo { get; set; }
        [DataMember]
    public virtual ICollection<ConsumeInfo> ConsumeInfo { get; set; }
        [DataMember]
    public virtual ICollection<MemberRecharge> MemberRecharge { get; set; }
        [DataMember]
    public virtual ICollection<RefundInfo> RefundInfo { get; set; }
        [DataMember]
    public virtual ICollection<ShiftItem> ShiftItem { get; set; }
    }
}
